spring:
    datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/wj?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: abc123
    #session 失效时间
    session:
      timeout: 86400